### PR TITLE
Update ChargeListener

### PR DESCRIPTION
**Pull request by 1stevengrant**
Emitting an event that the user has been charged and passing the submission data.

I could see a handful of these events being useful generally. 

In our case, we've added a listener to our own addon listening for the `user.charged` event and then with `$submission` the event is passing, we use that to submit the `$submission` data to an external CRM system.

I get that you won't want to be all things to all people but feel like emitting events is pretty simple.

### CODE REVIEW

**Comment by edalzell** [comment]
Thanks for this. The gents have moved away from the "string" version of events and towards using a class. I'd be more tempted to do a `ChargeSuccessful` event class and pass the user and the submission data?

Let me ponder a bit.

**Comment by 1stevengrant** [comment]
That's typically how I'd do it in a Laravel app but wasn't sure what that would look like in terms of another Statamic addon listening for the event.

**Comment by edalzell** [comment]
I use `CustomerCharge` & `CustomerSubscribed` events. Listen for `CustomerSubscribed::class` in your listener.

**Comment by 1stevengrant** [comment]
thanks for this @edalzell could there also be an event that emits the Statamic form submission data and not just the Stripe charge data?

**Comment by 1stevengrant** [comment]
in fact, I guess I could just listen for `Form.submission.created`

**Comment by edalzell** [comment]
For the `{{ charge:form }}` tag? If so, nope, that one doesn't use forms.

**Comment by 1stevengrant** [comment]
No, it's a native Statamic form so `Form.submission.created` works for us but I dare say that could be a handy thing to emit for `{{ charge:form }}` use.

**Comment by edalzell** [comment]
the `{{ charge:form }}` doesn't save stuff though so not sure what it would emit.

When someone asks for it, I'll look into it.

**Comment by 1stevengrant** [comment]
ah, got it. That makes sense then. As you were :)

**Pull request closed without merging**
